| Тип эклуатационного параметра СИИ Параметр СИИ Способ (методика) оценки и контроля | |:---:|:---:|:---:| | Оки 1-го и 2-го рода при принятии решений | Доля ложноположительных и ложноотрицательных результатов | Сравнение заключений ИИ с заключениями эксперта-патоморфолога или с результатами дополнительной лабораторной или инструментальной диагностики | |оказатели эффективности СИИ | Точность определения степени агрессивности опухолей РПЖ | Сравнение оценки по Глисону, проведённой ИИ, и оценки эксперта-патоморфолога | | Тип принимаемого решения | Оценка патоморфологического образца | Оценка результатов работы ИИ с использованием стандартной методики | | Набор заключений СИ | Диагностика РПЖ, оценка по системе Глисона | Проверка на репрезентативном наборе образцов | | Разнородность входных данных | Гистологические снимки разных стадий РПЖ | Проверка работы ИИ на датасетах разного содержания | | Формат входных данных | Цифровые гистологические изображения | Возможность работы системы с изображениями разного формата и качества | | Типнализируемого объекта | Биопсийные материалы простаты, послеоперационные материалы | Работа алгоритма с различными видами препаратов | | Способ обучения системы в процессе эксплуатации | Машинное обучение | Постоянное обновление базы данных для обучения и периодическое обучение системы | | Адаптируемость к новым типам данных при вводе СИИ в эксплуатацию | Способность алгоритма обрабатывать новые типы данных | Тестирование ИИ на новых данных | | Режим обработки данных при вводе СИ

# Домашняя работа №1: Знакомство с языком R

## Задание №1
В данных заданиях **запрещено использовать циклы!**

1. Даны целые числа `n` и `sz`, создайте вектор из повторяющихся чисел от 1 до `n` размера `sz`. e.g.: `n = 3`, `sz = 10` должно вернуть `c(1, 2, 3, 1, 2, 3, 1, 2, 3, 1)`.

In [ ]:
task1.1 <- function(n, sz) {
    v <- rep(1:n,sz)[1:sz]
    return(v)
}

In [ ]:
task1.1(3, 10)

[1] 1 2 3 1 2 3 1 2 3 1

2. Даны целые числа `n` и `sz`. Сгенерируйте вектор из случайных целых чисел от 1 до `n` и верните его. Выведите на экран, сколько раз сгенирировалась какое число.

In [ ]:
task1.2 <- function(n, sz) {
    v <- sample(1:n,sz,replace=TRUE)
    return(v)
}

In [ ]:
x <- task1.2(3,10)
x
table(x)

[1] 1 1 1 3 2 2 2 1 2 2

x
1 2 3 
4 5 1 

3. Дан вектор `x` и число `k`. Удалите из вектора все вхождения этого числа.

In [ ]:
task1.3 <- function(x, k) {
    v <- x[x!=k]
    return(v)
}

In [ ]:
x
task1.3(x,1)

[1] 1 1 1 3 2 2 2 1 2 2

[1] 3 2 2 2 2 2

4. Дано целое число `steps`, сгенерируйте вектор длины `steps` состоящий из чисел 1 и -1. Верните вектор и сумму чисел.

In [ ]:
task1.4 <- function(steps) {
    v <- sample(c(-1,1), steps, replace=TRUE)
    return(list(v, sum(v)))

}

In [ ]:
task1.4(10)

[[1]]
 [1] -1  1  1  1 -1  1 -1  1  1  1

[[2]]
[1] 4

5. *Смешанное распределение.* Дано число `sz`. Сгенерируйте вектор размера `sz` по следующему алгоритму: чтобы получить очередное число, вектора сначала бросается монетка, в одном случае нужно сгенерировать число из распределения $ \mathcal N(0, 1) $. Во втором случае из экспоненциального распределения с $ \lambda = 1 $.

In [ ]:
task1.5 <- function(sz) {
    v <- sample(c(0,1),sz,replace=TRUE)
    v[v==0] <- rnorm(length(v[v==0]),0,1)
    v[v==1] <- rexp(length(v[v==1]),1)
    return(v)
}

In [ ]:
task1.5(5)

[1]  0.3045912  1.2173902  1.5309480 -0.6283489  1.4816759

## Задание №2
Создайте указанные матрицы. В этих задачах нельзя использовать циклы. И вы должны избежать ручного ввода элементов матрицы, вместо этого используйте возможности R по конструированию матриц. Т.е., например, если вас попросили создать матрицу $ 10 \times 10 $, не перечисляейте в решении все 100 элементов этой матрицы. Представьте, что вас просят на самом деле создавать матрицы $ 1000 \times 1000 $. Маленькие матрицы в условии нужны для того, чтобы вам было проще отладить свою программу, увидев матрицы на экране целиком.

1. Создайте матрицу $ n \times n $, у которой в каждой клетке стоит 0 или 1 в шахматном порядке. e.g.: $ n = 5 $
$$
\begin{pmatrix}
    0 & 1 & 0 & 1 & 0 \\
    1 & 0 & 1 & 0 & 1 \\
    0 & 1 & 0 & 1 & 0 \\
  	1 & 0 & 1 & 0 & 1 \\
  	0 & 1 & 0 & 1 & 0
\end{pmatrix}
$$

In [ ]:
task2.1 <- function(n) {
    m <- matrix(c(rep(c(0,1),n)[1:n],rep(c(1,0),n)[1:n]),n,n,byrow=TRUE)
    return(m)
}

In [ ]:
task2.1(10)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 0    1    0    1    0    1    0    1    0    1    
 [2,] 1    0    1    0    1    0    1    0    1    0    
 [3,] 0    1    0    1    0    1    0    1    0    1    
 [4,] 1    0    1    0    1    0    1    0    1    0    
 [5,] 0    1    0    1    0    1    0    1    0    1    
 [6,] 1    0    1    0    1    0    1    0    1    0    
 [7,] 0    1    0    1    0    1    0    1    0    1    
 [8,] 1    0    1    0    1    0    1    0    1    0    
 [9,] 0    1    0    1    0    1    0    1    0    1    
[10,] 1    0    1    0    1    0    1    0    1    0

2. Даны натуральные числа $ n $ и $ m $. Сгенерируйте матрицу размера $ n \times m $, где первый столбец состоит из единиц, второй – из двоек, третий – из троек и т.д. Последний столбец содержит в себе значения $ m $.

In [ ]:
task2.2 <- function(n, m) {
    m <- matrix(c(1:m),n,m,byrow=TRUE)
    return(m)
}

In [ ]:
task2.2(5,6)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4    5    6   
[2,] 1    2    3    4    5    6   
[3,] 1    2    3    4    5    6   
[4,] 1    2    3    4    5    6   
[5,] 1    2    3    4    5    6

3. Создайте матрицу $ n \times n $ с подряд идущими числами от 1 до $ n^2 $. Пример для $ n = 10 $:
$$
\begin{pmatrix}
  	1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
  	11 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 \\
  	21 & 22 & 23 & 24 & 25 & 26 & 27 & 28 & 29 & 30 \\
  	\cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots \\
  	91 & 92 & 93 & 94 & 95 & 96 & 97 & 98 & 99 & 100
\end{pmatrix}
$$

In [ ]:
task2.3 <- function(n) {
    m <- matrix(c(1:(n*n)),n,n,byrow=TRUE)
    return(m)
}

In [ ]:
task2.3(10)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9    10  
 [2,] 11   12   13   14   15   16   17   18   19    20  
 [3,] 21   22   23   24   25   26   27   28   29    30  
 [4,] 31   32   33   34   35   36   37   38   39    40  
 [5,] 41   42   43   44   45   46   47   48   49    50  
 [6,] 51   52   53   54   55   56   57   58   59    60  
 [7,] 61   62   63   64   65   66   67   68   69    70  
 [8,] 71   72   73   74   75   76   77   78   79    80  
 [9,] 81   82   83   84   85   86   87   88   89    90  
[10,] 91   92   93   94   95   96   97   98   99   100

4. Даны числа $ n $, $ a $, $ b $. Создайте матрицу размера $ n \times n $, у которой на главной диагонали стоят числа $ a $, а строго над и под главной диагональю стоят числа $ b $. Остальные числа матрицы – нули. Пример матрицы для $ n = 4 $, $ a = 1 $, $ b = 2 $:
$$
\begin{pmatrix}
  	1 & 2 & 0 & 0 \\
  	2 & 1 & 2 & 0 \\
  	0 & 2 & 1 & 2 \\
  	0 & 0 & 2 & 1
\end{pmatrix}
$$

In [ ]:
task2.4 <- function(n, a, b) {
    m <- eye(n)*a
    m[lower.tri(m)] <- b*eye(n-1)[lower.tri(eye(n-1),diag=TRUE)]
    m[upper.tri(m)] <- b*eye(n-1)[upper.tri(eye(n-1),diag=TRUE)]
    return(m)
}

In [ ]:
task2.4(4,1,2)

ERROR: ignored

5. Дано натуральное число $ n $. Создайте следующую матрицу размера $ n \times n $: на главной диагонали матрицы чередуются 1 и 2. Дальше от каждой клетки главной диагонали направо и вниз расставляется то же числа, что и в самой этой клетке. Пример для $ n = 5 $:
$$
\begin{pmatrix}
  	1 & 1 & 1 & 1 & 1 \\
  	1 & 2 & 2 & 2 & 2 \\
  	1 & 2 & 1 & 1 & 1 \\
  	1 & 2 & 1 & 2 & 2 \\
  	1 & 2 & 1 & 2 & 1
\end{pmatrix}
$$

In [ ]:
task2.5 <- function(n) {
    m <- diag(c(1,2),n)
    x <- matrix(1+c(2:(n+1))%%2,n,n,byrow=TRUE)
    m[lower.tri(m)] <- x[lower.tri(x)]
    m[upper.tri(m)] <- t(x)[upper.tri(t(x))]
    return(m)
}

In [ ]:
task2.5(5)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    2    2    2    2   
[3,] 1    2    1    1    1   
[4,] 1    2    1    2    2   
[5,] 1    2    1    2    1

Кстати, а какой определитель у этой матрицы? А почему? Ответ укажите ниже.

+1/-1

Т.к. матрица симметричная при вычислении определителя с помощью приведения матрицы к треугольной получим на главной диагонали чередующуюся последовательность 1 1 -1 -1 1 1...

А определитель треугольной матрицы равен произведению чисел на главной диагонали.

## Задание №3
В данных задачах **запрещено использовать циклы!**

1. Дана матрица с четным числом строк. Поменяйте местами верхнюю половину строк матрицы и нижнюю половину.

In [ ]:
task3.1 <- function(n) {
    return(rbind(n[(1+dim(n)[1]/2):dim(n)[1],],n[1:(dim(n)[1]/2),]))
}

In [ ]:
n <- matrix(c(1:6),6,5)
n
task3.1(n)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 2    2    2    2    2   
[3,] 3    3    3    3    3   
[4,] 4    4    4    4    4   
[5,] 5    5    5    5    5   
[6,] 6    6    6    6    6

[,1] [,2] [,3] [,4] [,5]
[1,] 4    4    4    4    4   
[2,] 5    5    5    5    5   
[3,] 6    6    6    6    6   
[4,] 1    1    1    1    1   
[5,] 2    2    2    2    2   
[6,] 3    3    3    3    3

2. Дан вектор из целых чисел `x`, число `k` и матрица `A` чётного размера. Реализуйте функцию, которая возвращает следующие **два объекта**:
  * Матрицу `B`: необходимо поделить матрицу `A` пополам по вертикали и горизонтали и получить матрицу, соответствующую верхнему левому квадрату. Затем необходимо увеличить все нечетные числа полученной матрицы в два раза.
  * Вектор `y`: данный вектор содержит только те числа вектора `x`, которые делятся на `k`.

In [ ]:
task3.2 <- function(x, k, A) {
    B <- matrix(A[1:(dim(A)[1]/2),1:(dim(A)[2]/2)],dim(A)[1]/2,dim(A)[2]/2)
    B[B%%2!=0] <- B[B%%2!=0]*2
    y <- x[x%%k==0]
    return(list(B,y))
}

In [ ]:
x <- c(1:10)
k <- 3
A <- matrix(1:24,4,6)
x
A
task3.2(x,k,A)

[1]  1  2  3  4  5  6  7  8  9 10

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    5     9   13   17   21  
[2,] 2    6    10   14   18   22  
[3,] 3    7    11   15   19   23  
[4,] 4    8    12   16   20   24

[[1]]
     [,1] [,2] [,3]
[1,]    2   10   18
[2,]    2    6   10

[[2]]
[1] 3 6 9

3. Сделайте две функции:
  * `filter.multiples(a, k)` – удаляет из вектора `a` все числа, которые строго больше `k` и делятся на `k`;
  * `sieve(n)` – решето Эратосфена. Требуется вернуть вектор из простых чисел от 1 до `n`. Для этого создайте вектор всех целых чисел от 2 до `n`. С помощью предыдущей функции `filter.multiples` удалите сначла всё, что больше 2 и делится на 2. Потом всё, что больше 3 и делится на 3, потом все, что больше 5 (мы пропускаем 4, потому что оно уже было удалено на первом шаге) и делится на 5, и т.д. За подробностями смотрите, что такое [решето Эратосфена](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes).

In [ ]:
filter.multiples <- function(a, k) {
    return(a[a<=k | a%%k!=0])
}

sieve <- function(n) {
    a <- c(2:n)
    for (i in c(2:sqrt(n))){
      a <- filter.multiples(a,i)
    }
    return(a)
}


In [ ]:
sieve(30)

[1]  2  3  5  7 11 13 17 19 23 29

4. Дан столбец $ x $. Вернуть квадратную матрицу такого же размера, которая в $ i $-ой строке и $ j $-ом столбце содержит разность $ x_i - x_j $.

In [ ]:
task3.4 <- function(x) {
    m <- matrix(x,length(x),length(x)) - matrix(x,length(x),length(x),byrow=TRUE)
    return(m)
}

In [ ]:
task3.4(c(1:5))

[,1] [,2] [,3] [,4] [,5]
[1,] 0    -1   -2   -3   -4  
[2,] 1     0   -1   -2   -3  
[3,] 2     1    0   -1   -2  
[4,] 3     2    1    0   -1  
[5,] 4     3    2    1    0

5. Дана матрица-строка, например, `a <- c(1, 2, -2, 4)` и число `x`, например 1. Строка `a` задает коэффициенты многочлена, начиная с младшего, т.е. она соответствует многочлену $ 1 + 2x - 2x^2 + 4x^3 $. Посчитайте значение многочлена в точке `x`. Для приведенного примера ответ будет 5. Т.е. необходимо написать выражение через `a` и `x`, которое считает значение многочлена `a` в точке `x`.

In [ ]:
task3.5 <- function(a, x) {
    return(sum(x^(1:length(a)-1)*a))
}

In [ ]:
a <- c(1,2,-2,4)
x <- 2
task3.5(a,x)

[1] 29